# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1voYxV8LgkOfK9SoUTqG4_fNfTfAnxuZa
"""

print("- MOVIE BOOKING SYSTEM -")

username = input("Enter username: ")
password = input("Enter password: ")

if username == "neili" and password == "123":
    print("Login Successful!")

    while True:

        print("\n----- Movie Menu -----")
        print("1. Toy Story - Rs.1500")
        print("2. Nemo - Rs.1300")
        print("3. Barbie - Rs.1400")
        print("4. Exit")

        choice = int(input("Enter movie choice: "))

        if choice == 4:
            print("Thank you for using the Movie Booking System!")
            break

        if choice == 1:
            movie = "Toy Story"
            price = 1500

        elif choice == 2:
            movie = "Nemo"
            price = 1300

        elif choice == 3:
            movie = "Barbie"
            price = 1400

        else:
            print("Invalid choice. Please try again.")
            continue

        tickets = int(input("Enter how many tickets you want to buy: "))

        total = tickets * price

        if tickets > 5:
            discount = total * 0.05
        else:
            discount = 0

        final = total - discount

        print("\n------ BILL ------")
        print("Movie:", movie)
        print("Tickets:", tickets)
        print("Total: Rs.", total)
        print("Discount: Rs.", discount)
        print("Amount to Pay: Rs.", final)

        if tickets > 5:
            print("Congratulations! You received a 5% discount.")
        else:
            print("Buy more than 5 tickets to receive a 5% discount.")

else:
    print("Invalid Login! Please Try Again.")